//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Expense_Tracker.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.expenses = new HashSet<expense>();
        }
    
        public int CAT_id { get; set; }
        public string CATEGORY_TITLE { get; set; }
        public int CATEGORY_AMOUNT { get; set; }
    
        public virtual ICollection<expense> expenses { get; set; }
    }
}
