//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Expense_Tracker.context
{
    using System;
    using System.Collections.Generic;
    
    public partial class expense
    {
        public int id { get; set; }
        public string EXPENSE_TITLE { get; set; }
        public int EXPENSE_AMOUNT { get; set; }
        public int CAT_id { get; set; }
        public string DISCRIPTION { get; set; }
        public System.DateTime DATE_TIME { get; set; }
    
        public virtual category category { get; set; }
    }
}
